# Generated by Django 2.0.6 on 2019-05-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, null=True)),
                ('dangdang_price', models.FloatField(null=True)),
                ('market_price', models.FloatField(null=True)),
                ('sales', models.CharField(max_length=40, null=True)),
                ('storage', models.CharField(max_length=40, null=True)),
                ('pushish_time', models.DateField(null=True)),
                ('editer_commond', models.IntegerField(null=True)),
                ('anthor', models.CharField(max_length=40, null=True)),
                ('pics', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, null=True)),
                ('parent_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('receive_address', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, null=True)),
                ('sub_total', models.FloatField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TBook')),
            ],
            options={
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, null=True)),
                ('username', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainapp.TOrder')),
                ('recever', models.CharField(max_length=40, null=True)),
                ('receve_address', models.CharField(max_length=40, null=True)),
                ('zip_code', models.CharField(max_length=6, null=True)),
                ('tel', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TUser')),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.AddField(
            model_name='torderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TOrder'),
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TCategory'),
        ),
    ]
