# Generated by Django 2.0.6 on 2019-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbook',
            name='c_introducete',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tbook',
            name='directory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tbook',
            name='n_introducete',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tbook',
            name='pages',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
