# Generated by Django 2.0.6 on 2019-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190516_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbook',
            name='directory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='storage',
            field=models.IntegerField(max_length=40, null=True),
        ),
    ]
