# Generated by Django 2.0.6 on 2019-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190516_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbook',
            name='storage',
            field=models.IntegerField(null=True),
        ),
    ]
