# Generated by Django 2.0.6 on 2019-05-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190517_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
