# Generated by Django 2.0.6 on 2019-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190517_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
