# Generated by Django 2.0.6 on 2019-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190520_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbook',
            name='pushish_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
