# Generated by Django 2.0.6 on 2019-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190520_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='torder',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='torder',
            name='book_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='torder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
