# Generated by Django 2.0.6 on 2019-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190523_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='torder',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
