# Generated by Django 2.0.6 on 2019-05-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_torder_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
        migrations.AlterField(
            model_name='tuser',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TUser', verbose_name='关联用户'),
        ),
    ]
