# Generated by Django 2.0.6 on 2019-05-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190524_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_string',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TUser', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TUser'),
        ),
    ]
