# Generated by Django 2.0.6 on 2019-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190524_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_string',
            name='code_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
