# Generated by Django 2.0.6 on 2019-05-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_confirm_string_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TUser'),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TCategory'),
        ),
        migrations.AlterField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TUser'),
        ),
        migrations.AlterField(
            model_name='torderitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TBook'),
        ),
        migrations.AlterField(
            model_name='torderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TOrder'),
        ),
    ]
